'use client';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
import {ProfileForm,PaymentSettings,ManualPayment,ManualReview} from './payment-controls';
const money=(n:number)=>`₹${(n/100).toLocaleString('en-IN')}`;
const labels:Record<string,string>={rent:'Rent',buy:'Buy',monthly:'Monthly Subscription',yearly:'Yearly Subscription',paid:'सक्रिय',pending:'भुगतान की प्रतीक्षा',creating:'तैयार हो रहा है',error:'अधूरा अनुरोध',refunded:'Refund हुआ',expired:'अवधि समाप्त',rejected:'अस्वीकार किया गया'};
const term=(o:any)=>o.kind==='monthly'?'30 दिन · Auto-renew बंद':o.kind==='yearly'?'365 दिन · Auto-renew बंद':o.kind==='rent'?`${o.duration_days} दिन · भुगतान की पुष्टि से`:'खरीदी हुई वीडियो की पहुँच';
async function req(path:string,method='GET',body?:object){const r=await fetch(path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'अनुरोध पूरा नहीं हुआ।');return d}
let checkoutScript:Promise<void>|null=null;
function loadCheckout(){if((window as any).Razorpay)return Promise.resolve();if(!checkoutScript)checkoutScript=new Promise<void>((resolve,reject)=>{const s=document.createElement('script'),timer=setTimeout(()=>{s.remove();checkoutScript=null;reject(new Error('भुगतान स्क्रीन लोड नहीं हुई। फिर कोशिश करें।'))},15000);s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>{clearTimeout(timer);resolve()};s.onerror=()=>{clearTimeout(timer);checkoutScript=null;s.remove();reject(new Error('भुगतान स्क्रीन लोड नहीं हुई।'))};document.body.appendChild(s)});return checkoutScript;}
async function checkout(offer:any){await loadCheckout();const order=await req('/api/orders','POST',{offerId:offer.id,requestId:crypto.randomUUID()});return new Promise<void>((resolve,reject)=>{const r=new (window as any).Razorpay({key:order.key,order_id:order.orderId,amount:order.amount,currency:'INR',name:'Gondwana OTT',description:order.title,theme:{color:'#b68c42'},modal:{ondismiss:()=>resolve()},handler:async(result:any)=>{try{const v=await req('/api/payments/verify','POST',{id:order.id,...result});toast(v.status==='paid'?'भुगतान सफल। पहुँच चालू है।':'पुष्टि की प्रतीक्षा है। मेरा खाता में स्थिति जाँचें।');resolve()}catch(e){reject(e)}}});r.on('payment.failed',()=>toast.error('भुगतान पूरा नहीं हुआ। पैसा कटा हो तो मेरा खाता में स्थिति जाँचें।'));r.open()});}
function Offers({offers,ready,manualReady=false,signedIn=true,showProfile=true,onPaid}:{offers:any[];ready:boolean;manualReady?:boolean;signedIn?:boolean;showProfile?:boolean;onPaid:()=>Promise<void>}){const [busy,setBusy]=useState(''),[manualId,setManualId]=useState(''),[profileReady,setProfileReady]=useState(false),[profileError,setProfileError]=useState('');const checkProfile=useCallback(async()=>{if(!signedIn)return;try{const d=await req('/api/profile');setProfileReady(!!d.profile);setProfileError('')}catch(e){setProfileError((e as Error).message)}},[signedIn]);useEffect(()=>{checkProfile();window.addEventListener('ott-profile-saved',checkProfile);return()=>window.removeEventListener('ott-profile-saved',checkProfile)},[checkProfile]);async function buy(o:any,manual=false){setBusy(o.id);try{if(manual){const d=await req('/api/orders','POST',{offerId:o.id,requestId:crypto.randomUUID(),method:'manual'});setManualId(d.id)}else await checkout(o);await onPaid()}catch(e){toast.error((e as Error).message);await onPaid()}finally{setBusy('')}}return <>{showProfile&&signedIn&&!profileReady&&<ProfileForm onSaved={()=>{checkProfile()}}/>}{profileError&&<p role="alert">{profileError}</p>}{!ready&&!manualReady&&<p className="notice">Admin ने अभी भुगतान चालू नहीं किया है।</p>}{offers.map(o=><article className="account-box" key={o.id}><h3>{o.title}</h3><p><strong>{labels[o.kind]} · {money(o.price_paise)}</strong></p><p className="subtle">{term(o)}</p>{signedIn?<div className="flex flex-wrap gap-2">{manualReady&&<Button disabled={!!busy||!profileReady} variant="outline" onClick={()=>buy(o,true)}>सीधा UPI · Admin जाँच</Button>}{ready&&<Button className="button-primary" disabled={!!busy||!profileReady} onClick={()=>buy(o)}>Gateway · ऑटोमैटिक</Button>}{!!busy&&<span role="status">कृपया प्रतीक्षा करें…</span>}</div>:<Button asChild><a href="/signin-with-chatgpt?return_to=/" target="_top">साइन इन करके प्लान चुनें</a></Button>}</article>)}{manualId&&<ManualPayment id={manualId} onClose={()=>setManualId('')} onSaved={onPaid}/>}</>}
export function PaymentGate({entryId,signedIn,children}:{entryId:string;signedIn:boolean;children:ReactNode}){const [data,setData]=useState<any>(null),[error,setError]=useState('');const load=useCallback(async()=>{try{setData(await req('/api/access/'+entryId));setError('')}catch(e){setError((e as Error).message)}},[entryId]);useEffect(()=>{load();window.addEventListener('ott-access-changed',load);return()=>window.removeEventListener('ott-access-changed',load)},[load]);if(error)return <p className="notice" role="alert">{error}<Button onClick={load}>फिर कोशिश करें</Button></p>;if(!data)return <p role="status">वीडियो की पहुँच जाँच रहे हैं…</p>;if(data.allowed)return <>{children}</>;return <section><h2>इस वीडियो के लिए प्लान चुनें</h2><Offers offers={data.offers} ready={data.gateway.ready} manualReady={data.gateway.manualReady} signedIn={signedIn} onPaid={load}/>{!data.offers.length&&<p className="subtle">इस वीडियो का प्लान अभी उपलब्ध नहीं है।</p>}<Button variant="outline" onClick={load}>भुगतान के बाद पहुँच जाँचें</Button></section>}
export function CommercePanel({movies}:{movies:{id:string;song:string;content_type:string}[]}){
 const [data,setData]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[entryId,setEntryId]=useState(''),[kind,setKind]=useState('rent'),[price,setPrice]=useState(''),[days,setDays]=useState('7'),[busy,setBusy]=useState(false),[error,setError]=useState('');const videos=movies.filter(m=>['movie','series'].includes(m.content_type)),sub=['monthly','yearly'].includes(kind);
 const load=useCallback(async()=>{try{const [a,b]=await Promise.all([req('/api/offers'),req('/api/orders')]);setData(a);setOrders(b.orders);setError('')}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{load();const t=setInterval(()=>{if(document.visibilityState==='visible')load()},20000);return()=>clearInterval(t)},[load]);async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await req('/api/offers','PUT',{entryId:sub?null:entryId,kind,pricePaise:Math.round(Number(price)*100),durationDays:Number(days)});await load();setPrice('');toast.success('प्लान सेव हुआ। वीडियो की पहुँच नीचे तय करें।')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}async function patch(body:object){setBusy(true);try{await req('/api/offers','PATCH',body);await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div className="upload-panel"><h2>Rent, Buy और Subscription</h2>{error&&<p className="notice error" role="alert">{error}<Button onClick={load}>फिर कोशिश करें</Button></p>}<PaymentSettings onSaved={load}/><form onSubmit={save}><fieldset disabled={busy}><label className="field">प्लान<select value={kind} onChange={e=>setKind(e.target.value)}>{['rent','buy','monthly','yearly'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>{!sub&&<label className="field">फिल्म / एपिसोड<select required value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">वीडियो चुनें</option>{videos.map(m=><option key={m.id} value={m.id}>{m.song}</option>)}</select></label>}<label className="field">कीमत (₹)<Input type="number" min="1" max="1000000" step="0.01" required value={price} onChange={e=>setPrice(e.target.value)}/></label>{kind==='rent'&&<label className="field">Rent अवधि (दिन)<Input type="number" min="1" max="90" required value={days} onChange={e=>setDays(e.target.value)}/></label>}{sub&&<p className="subtle">{kind==='monthly'?'30':'365'} दिन। केवल Subscription में शामिल वीडियो मिलेंगी। Auto-renew बंद रहेगा।</p>}<Button type="submit" className="button-primary">प्लान सेव करें</Button></fieldset></form>
 <h3 className="mt-8">वीडियो की पहुँच</h3><p className="subtle">शुरू में वीडियो Free रहती हैं। Paid करने पर बिना मान्य खरीद या प्लान के वीडियो नहीं चलेगी। सीधा UPI या Gateway में से कम से कम एक तरीका चालू करें।</p>{videos.map(v=>{const a=data?.access.find((x:any)=>x.entry_id===v.id)||{paid:0,subscription:0};return <article key={v.id} className="account-box"><h3>{v.song}</h3><label className="field">दर्शकों की पहुँच<select disabled={busy} value={!a.paid?'free':a.subscription?'subscription':'paid'} onChange={e=>patch({action:'access',entryId:v.id,paid:e.target.value!=='free',subscription:e.target.value==='subscription'})}><option value="free">Free</option><option value="paid">केवल Rent / Buy</option><option value="subscription">Subscription या Rent / Buy</option></select></label></article>})}
 <h3 className="mt-8">सेव किए गए प्लान</h3>{data?.offers.map((o:any)=><article className="account-box" key={o.id}><h3>{o.title}</h3><p>{labels[o.kind]} · {money(o.price_paise)} · {term(o)}</p><label className="flex gap-3 items-center"><Switch disabled={busy} checked={!!o.enabled} onCheckedChange={enabled=>patch({id:o.id,enabled})}/>{o.enabled?'ON':'OFF'}</label></article>)}<h3 className="mt-8">भुगतान रिकॉर्ड · {orders.filter(o=>o.method==='manual'&&o.status==='pending'&&o.utr).length} UPI जाँच बाकी</h3><Button variant="outline" onClick={load}>सूची ताज़ा करें</Button><p className="subtle">Refund अपने Razorpay Dashboard से करें। पूर्ण refund की पुष्टि पर वीडियो की पहुँच बंद होगी। Revenue Sharing का हिसाब अलग टैब में है; स्वचालित निर्माता भुगतान अभी नहीं जुड़ा है।</p>{orders.length?orders.map(o=><article className="account-box" key={o.id}><h3>{o.title} · {money(o.amount)}</h3><p>{labels[o.kind]} · {labels[o.status]||o.status} · {o.method==='manual'?'सीधा UPI':'Gateway'}</p><p>{o.customer_name||'पुराना ऑर्डर'} · {o.customer_mobile} · {o.customer_city}</p><p className="subtle">{o.customer_email}<br/>{new Date(o.created_at).toLocaleString('hi-IN',{timeZone:'Asia/Kolkata'})} IST</p>{o.method==='manual'&&<ManualReview order={o} onSaved={load}/>}<small className="break-all">Order: {o.id}<br/>Payment: {o.payment_id||'पुष्टि बाकी'}</small></article>):<p className="subtle">अभी कोई भुगतान रिकॉर्ड नहीं है।</p>}</div>
}
export function AccountCommerce(){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[checking,setChecking]=useState(''),[manualId,setManualId]=useState('');const load=useCallback(async()=>{try{setData(await req('/api/account'));setError('')}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{load();const t=setInterval(()=>{if(document.visibilityState==='visible')load()},20000);return()=>clearInterval(t)},[load]);async function check(id:string){setChecking(id);try{const d=await req('/api/orders','PATCH',{id});toast(d.message);await load()}catch(e){toast.error((e as Error).message)}finally{setChecking('')}}return <div className="account-box"><h2>मेरे प्लान और खरीद</h2><ProfileForm/>{manualId&&<ManualPayment id={manualId} onClose={()=>setManualId('')} onSaved={load}/>}{error&&<p role="alert" className="notice">{error}<Button onClick={load}>फिर कोशिश करें</Button></p>}{!data?<p>खाते की जानकारी लोड हो रही है…</p>:<><h3>मेरी खरीद और भुगतान</h3>{data.orders.length?data.orders.map((o:any)=><article className="account-box" key={o.id}><h3>{o.title}</h3><p>{labels[o.kind]} · {money(o.amount)} · {labels[o.status]||o.status}</p>{o.expires_at&&<p>वैधता: {new Date(o.expires_at).toLocaleString('hi-IN',{timeZone:'Asia/Kolkata'})} IST</p>}{o.payment_id&&<small className="break-all">भुगतान संदर्भ: {o.payment_id}</small>}{o.method==='manual'&&<Button variant="outline" onClick={()=>setManualId(o.id)}>UPI विवरण / UTR</Button>}{o.status==='pending'&&<Button disabled={!!checking} variant="outline" onClick={()=>check(o.id)}>{checking===o.id?'जाँच रहे हैं…':'भुगतान की स्थिति जाँचें'}</Button>}</article>):<p className="subtle">अभी कोई खरीद नहीं है।</p>}<h3>उपलब्ध प्लान</h3><Offers offers={data.offers} ready={data.gateway.ready} manualReady={data.gateway.manualReady} showProfile={false} onPaid={load}/>{!data.offers.length&&<p className="subtle">अभी कोई प्लान उपलब्ध नहीं है।</p>}</>}</div>}
