'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {genres} from '@/lib/catalog';
import type {Competition} from './event-manager';
import type {EpisodeGroup} from './episode-browser';
import type {VideoEntry} from './video-shelves';
export default function EpisodeManager({events,groups,entries,onSaved}:{events:Competition[];groups:EpisodeGroup[];entries:VideoEntry[];onSaved:()=>Promise<void>}){
 const [parent,setParent]=useState('series'),[series,setSeries]=useState(''),[genre,setGenre]=useState<string>(genres[0]),[season,setSeason]=useState('1'),[number,setNumber]=useState('1'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false);
 const event=events.find(e=>e.id===parent),filtered=groups.filter(g=>event?g.event_id===event.id:!g.event_id&&g.series_title===series.trim());
 async function save(body:object,method='PATCH'){setBusy(true);try{const r=await fetch('/api/episodes',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'एपिसोड सेव नहीं हुआ।');await onSaved();toast.success('एपिसोड की जानकारी सेव हुई।');return true}catch(e){toast.error((e as Error).message);return false}finally{setBusy(false)}}
 return <div className="upload-panel"><h2>सीज़न / एपिसोड प्रबंधन</h2><p className="subtle">पहले एपिसोड बनाएँ, फिर अपलोड में उसे चुनें। वीडियो आने तक Coming Soon दिखेगा।</p><label className="field">सीरीज़ या इवेंट<select value={parent} disabled={busy} onChange={e=>setParent(e.target.value)}><option value="series">वेब सीरीज़</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>{event?<label className="field">इवेंट में वीडियो दिखाने का तरीका<select value={event.episode_mode?'episodes':'direct'} disabled={busy} onChange={e=>save({action:'mode',eventId:event.id,enabled:e.target.value==='episodes'})}><option value="direct">सीधी परफ़ॉर्मेंस सूची</option><option value="episodes">एपिसोड के अंदर परफ़ॉर्मेंस</option></select></label>:<><label className="field">सीरीज़ का नाम<Input value={series} maxLength={150} onChange={e=>setSeries(e.target.value)} list="series-names"/><datalist id="series-names">{[...new Set([...entries.filter(e=>e.content_type==='series').map(e=>e.series_title),...groups.filter(g=>!g.event_id).map(g=>g.series_title)])].map(s=><option key={s}>{s}</option>)}</datalist></label><label className="field">कैटेगरी<select value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(g=><option key={g}>{g}</option>)}</select></label></>}
 <form onSubmit={async e=>{e.preventDefault();if(await save({eventId:event?.id,seriesTitle:series,genre,season:Number(season),episode:Number(number),title,description},'POST')){setTitle('');setDescription('');setNumber(String(Number(number)+1))}}}><div className="form-grid">{!event&&<label className="field">सीज़न<Input type="number" min={1} max={999} required value={season} onChange={e=>setSeason(e.target.value)}/></label>}<label className="field">एपिसोड नंबर<Input type="number" min={1} max={9999} required value={number} onChange={e=>setNumber(e.target.value)}/></label></div><label className="field">एपिसोड का नाम<Input required maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="ऑडिशन / राउंड 1 / फिनाले"/></label><label className="field">विवरण<textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></label><Button type="submit" disabled={busy||(!event&&!series.trim())}>एपिसोड बनाएँ</Button></form>
 {event&&<p className="subtle">वोट देने के लिए इवेंट और एपिसोड दोनों की वोटिंग ON और इवेंट का समय चालू होना चाहिए। पूरे कार्यक्रम की वीडियो पर वोट नहीं होते।</p>}{filtered.map(g=><article className="account-box" key={g.id}><h3>{event?'':`सीज़न ${g.season} · `}एपिसोड {g.episode} · {g.title}</h3><p className="subtle">{g.description}</p>{event&&<label className="field">इस एपिसोड की वोटिंग<select aria-label={`${g.title} वोटिंग`} value={g.voting_enabled?'on':'off'} disabled={busy} onChange={e=>save({action:'voting',id:g.id,enabled:e.target.value==='on'})}><option value="off">OFF — दर्शकों से छिपी</option><option value="on">ON</option></select></label>}<p>{entries.filter(e=>e.episode_group_id===g.id).length} जुड़ी वीडियो</p><label className="field">मौजूदा वीडियो इस एपिसोड में जोड़ें<select value="" disabled={busy} onChange={e=>{if(e.target.value)save({action:'assign',entryId:e.target.value,id:g.id})}}><option value="">वीडियो चुनें</option>{entries.filter(e=>(event?e.event_id===event.id:e.content_type==='series'&&e.series_title===series.trim())&&e.episode_group_id!==g.id).map(e=><option key={e.id} value={e.id}>{e.song}</option>)}</select></label></article>)}</div>
}
