'use client';
import {useState,type ReactNode} from 'react';
import {Artwork,VideoShelf,type VideoEntry} from './video-shelves';
import {displayGenre} from '@/lib/catalog';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type EpisodeGroup={id:string;event_id:string|null;series_title:string;genre:string;season:number;episode:number;title:string;description:string;duration_seconds:number;voting_enabled:number};
export function SeriesShelf({title,entries,groups,genre,onSelect}:{title:string;entries:VideoEntry[];groups:EpisodeGroup[];genre?:string;onSelect:(e:VideoEntry)=>void}){
 const [opened,setOpened]=useState(''),[season,setSeason]=useState(1);
 const seriesEntries=entries.filter(e=>e.content_type==='series');const seriesGroups=groups.filter(g=>!g.event_id);
 const names=[...new Set([...seriesEntries.map(e=>e.series_title),...seriesGroups.map(g=>g.series_title)])].filter(name=>!genre||displayGenre(seriesGroups.find(g=>g.series_title===name)?.genre||seriesEntries.find(e=>e.series_title===name)?.genre||'')===genre);
 const videos=seriesEntries.filter(e=>e.series_title===opened);const plans=seriesGroups.filter(g=>g.series_title===opened);
 const seasons=[...new Set([...videos.map(e=>e.season||1),...plans.map(g=>g.season)])].sort((a,b)=>a-b);
 const numbers=[...new Set([...videos.filter(e=>e.season===season).map(e=>e.episode||1),...plans.filter(g=>g.season===season).map(g=>g.episode)])].sort((a,b)=>a-b);
 return <><section className="video-shelf portrait-shelf"><div className="shelf-heading"><h2>{title}</h2></div>{names.length?<div className="shelf-track">{names.map(name=>{const first=seriesEntries.filter(e=>e.series_title===name).sort((a,b)=>(a.season||1)-(b.season||1)||(a.episode||1)-(b.episode||1))[0];return <article className="shelf-card" key={name}><button className="shelf-artwork" onClick={()=>{setOpened(name);setSeason(Math.min(...seriesEntries.filter(e=>e.series_title===name).map(e=>e.season||1),...seriesGroups.filter(g=>g.series_title===name).map(g=>g.season)))}}>{first?<Artwork entry={first} portrait/>:<span className="episode-placeholder">{name}<small>COMING SOON</small></span>}</button><button className="shelf-title" onClick={()=>{setOpened(name);setSeason(Math.min(...seriesEntries.filter(e=>e.series_title===name).map(e=>e.season||1),...seriesGroups.filter(g=>g.series_title===name).map(g=>g.season)))}}>{name}</button><p className="shelf-meta">सीज़न और एपिसोड देखें</p></article>})}</div>:<p className="shelf-empty">वेब सीरीज़ जल्द जोड़ी जाएँगी।</p>}</section><Dialog open={!!opened} onOpenChange={v=>{if(!v)setOpened('')}}><DialogContent className="episode-dialog"><DialogHeader><DialogTitle>{opened}</DialogTitle><DialogDescription>सीज़न चुनें और एपिसोड देखें।</DialogDescription></DialogHeader><label className="field">सीज़न<select value={season} onChange={e=>setSeason(Number(e.target.value))}>{seasons.map(s=><option key={s} value={s}>सीज़न {s}</option>)}</select></label>{numbers.map(n=>{const plan=plans.find(g=>g.season===season&&g.episode===n),items=videos.filter(e=>e.season===season&&e.episode===n);return <div key={n}>{items.length?<VideoShelf title={`एपिसोड ${n} · ${plan?.title||items[0].song}`} entries={items} onSelect={e=>{setOpened('');onSelect(e)}}/>:<div className="shelf-empty"><h3>एपिसोड {n} · {plan?.title}</h3><p>{plan?.description}</p><span className="badge">Coming Soon</span></div>}{plan?.description&&items.length>0&&<p className="subtle">{plan.description}</p>}</div>})}</DialogContent></Dialog></>;
}
export function EventEpisodes({title,entries,groups,onSelect,renderVote}:{title:string;entries:VideoEntry[];groups:EpisodeGroup[];onSelect:(e:VideoEntry)=>void;renderVote:(e:VideoEntry)=>ReactNode}){return <section><h2>{title} · एपिसोड</h2>{[...groups].sort((a,b)=>a.episode-b.episode).map(g=>{const items=entries.filter(e=>e.episode_group_id===g.id);return <div key={g.id}><VideoShelf title={`एपिसोड ${g.episode} · ${g.title}`} entries={items} onSelect={onSelect} renderVote={renderVote}/>{!!g.description&&<p className="subtle">{g.description}</p>}{!items.length&&<p className="badge">Coming Soon</p>}</div>})}{!groups.length&&<p className="shelf-empty">एपिसोड जल्द जोड़े जाएँगे।</p>}{entries.some(e=>!e.episode_group_id)&&<VideoShelf title="अन्य प्रकाशित परफ़ॉर्मेंस" entries={entries.filter(e=>!e.episode_group_id)} onSelect={onSelect} renderVote={renderVote}/>}</section>}
