'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Input} from '@/components/ui/input';
export type Competition={id:string;name:string;type_label?:string;type:'singing'|'dance'|'other';description:string;rules:string;starts_at:number;ends_at:number;has_poster:number;voting_enabled:number;candidate_voting:number;episode_mode:number;created_at:number};
export const eventStatus=(event:Competition,now:number)=>now<event.starts_at?'आगामी':now>=event.ends_at?'समाप्त':'चालू';
export const eventDate=(time:number)=>new Intl.DateTimeFormat('hi-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(time);
export function EventCreator({initialType,onCreated}:{initialType:'singing'|'dance'|'other';onCreated:(id:string,type:'singing'|'dance'|'other')=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const start=Date.parse(String(data.get('start'))+'+05:30'),end=Date.parse(String(data.get('end'))+'+05:30');if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end<=Date.now()){setError('वोटिंग का समाप्ति समय शुरुआत के बाद और भविष्य में रखें।');return}data.set('startsAt',String(start));data.set('endsAt',String(end));const poster=data.get('poster');if(poster instanceof File&&poster.size>2*1024*1024){setError('पोस्टर 2 MB से छोटा रखें।');return}setBusy(true);setError('');try{const res=await fetch('/api/events',{method:'POST',body:data});const result=await res.json() as {id:string;error?:string};if(!res.ok)throw new Error(result.error||'इवेंट सेव नहीं हुआ।');await onCreated(result.id,'other');form.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="upload-panel"><h2 className="text-2xl font-semibold mb-2">इवेंट बनाएँ</h2><p className="subtle mb-6">इवेंट बनते ही दर्शकों को दिखेगा। वीडियो जोड़ें। वोटिंग शुरू में बंद रहेगी; वोटिंग प्रबंधन में ON करने पर तय समय में खुलेगी।</p><form onSubmit={submit}><fieldset disabled={busy}><div className="field"><label htmlFor="event-name">इवेंट का नाम *</label><Input id="event-name" name="name" required maxLength={150} placeholder="जैसे: गोंडवाना डांस चैंपियनशिप 2026"/></div><div className="field"><label htmlFor="event-type">इवेंट का प्रकार *</label><Input id="event-type" name="typeLabel" required maxLength={80} placeholder="जैसे: सिंगिंग, डांस, कबड्डी, कविता"/></div><div className="field"><label htmlFor="event-description">विवरण</label><textarea id="event-description" name="description" rows={3} maxLength={2000} placeholder="प्रतियोगिता के बारे में बताएँ"/></div><div className="field"><label htmlFor="event-rules">प्रतियोगिता के नियम</label><textarea id="event-rules" name="rules" rows={4} maxLength={3000} placeholder="पात्रता, पुरस्कार और परिणाम की जानकारी"/><small className="subtle">उम्मीदवार / वोट टैब से नामवार वोटिंग चालू करें: प्रति खाते, प्रति राउंड एक उम्मीदवार को वोट।</small></div><div className="form-grid"><div className="field"><label htmlFor="event-start">वोटिंग शुरू — IST *</label><Input id="event-start" name="start" type="datetime-local" required/></div><div className="field"><label htmlFor="event-end">वोटिंग समाप्त — IST *</label><Input id="event-end" name="end" type="datetime-local" required/></div></div><div className="field"><label htmlFor="event-poster">पोस्टर (वैकल्पिक)</label><input id="event-poster" name="poster" type="file" accept="image/png,image/jpeg"/><small className="subtle">JPG या PNG · अधिकतम 2 MB</small></div>{error&&<p className="notice error" role="alert">{error}</p>}<Button type="submit" className="button-primary" disabled={busy}>{busy?'इवेंट सेव हो रहा है…':'इवेंट बनाएँ और प्रकाशित करें'}</Button></fieldset></form></div>
}

export function VotingManager({events,onSaved}:{events:Competition[];onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState<string|null>(null),[error,setError]=useState('');
 async function toggle(event:Competition,enabled:boolean){setBusy(event.id);setError('');try{const res=await fetch(`/api/events/${event.id}/voting`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||'सेव नहीं हुआ।');await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 return <div><h2 className="text-2xl font-semibold">इवेंट वोटिंग</h2><p className="subtle">ON करने पर तय समय में वोट दे सकेंगे। OFF करने पर वोट का विकल्प छिप जाएगा। पुराने वोट सुरक्षित रहेंगे।</p>{error&&<p className="notice error" role="alert">{error}</p>}{events.map(event=><div className="artwork-admin-row" key={event.id}><h3>{event.name}</h3><p className="subtle">{event.type_label||(event.type==='dance'?'डांस':event.type==='singing'?'सिंगिंग':'अन्य इवेंट')} · {eventDate(event.starts_at)} — {eventDate(event.ends_at)} (IST)</p><label className="flex items-center gap-3 min-h-11"><Switch checked={!!event.voting_enabled} disabled={busy!==null} onCheckedChange={enabled=>toggle(event,enabled)} aria-label={`${event.name} वोटिंग`}/><span>वोटिंग {event.voting_enabled?'ON':'OFF'}{busy===event.id?' · सेव हो रहा है…':''}</span></label></div>)}{!events.length&&<p className="notice">पहले इवेंट बनाएँ।</p>}</div>
}
