'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import type {VideoEntry} from './video-shelves';
let pendingRelease:Promise<void>=Promise.resolve();
export default function ResumePlayer({entry,signedIn,next,onNext}:{entry:VideoEntry;signedIn:boolean;next?:VideoEntry;onNext:(e:VideoEntry)=>void}){
 const ref=useRef<HTMLVideoElement>(null),sid=useRef(''),position=useRef(0),duration=useRef(0),watched=useRef(0),lastTick=useRef(0),lastPosition=useRef(0),wantPlay=useRef(false),queue=useRef(Promise.resolve()),mounted=useRef(true),starting=useRef(false);
 const [token,setToken]=useState(''),[message,setMessage]=useState(''),[buffering,setBuffering]=useState(false),[offline,setOffline]=useState(false),[saver,setSaver]=useState(false),[retry,setRetry]=useState(0),[needSignIn,setNeedSignIn]=useState(false);
 function snapshot(){const v=ref.current;if(v){position.current=Math.floor(v.currentTime||0);duration.current=Number.isFinite(v.duration)?Math.ceil(v.duration):0}}
 async function report(ended=false){snapshot();const id=sid.current;if(!id)return;const body=JSON.stringify({id,position:position.current,duration:duration.current,watched:Math.min(30,Math.floor(watched.current)),completed:!!ref.current?.ended,ended});watched.current=0;queue.current=queue.current.then(async()=>{const r=await fetch('/api/playback',{method:'PATCH',keepalive:ended,headers:{'Content-Type':'application/json'},body});if(!r.ok&&mounted.current){const data=await r.json() as {error:string};setMessage(data.error);if(r.status===401||r.status===402||r.status===403){if(r.status===401)setNeedSignIn(true);ref.current?.pause();setToken('');sid.current='';window.dispatchEvent(new Event('ott-access-changed'))}}}).catch(()=>{if(mounted.current)setMessage('प्रगति भेजने के लिए कनेक्शन की प्रतीक्षा है।')});if(signedIn&&duration.current>0){const progress=JSON.stringify({position:Math.min(position.current,duration.current),duration:duration.current,completed:!!ref.current?.ended});queue.current=queue.current.then(async()=>{const r=await fetch(`/api/progress/${entry.id}`,{method:'PUT',keepalive:ended,headers:{'Content-Type':'application/json'},body:progress});if(!r.ok&&mounted.current)setMessage('देखने की प्रगति सेव नहीं हुई।')}).catch(()=>{});}await queue.current}
 useEffect(()=>{mounted.current=true;try{setSaver(localStorage.getItem('ott-data-saver')==='1'||!!(navigator as any).connection?.saveData)}catch{}setOffline(!navigator.onLine);return()=>{mounted.current=false}},[]);
 useEffect(()=>{let active=true;async function start(){if(starting.current)return;starting.current=true;try{await pendingRelease;if(sid.current){await report(true);sid.current=''}if(signedIn&&retry===0){try{const r=await fetch(`/api/progress/${entry.id}`,{cache:'no-store'});if(r.ok){const d=await r.json() as any;position.current=d.progress&&!d.progress.completed?d.progress.position_seconds:0}}catch{}}const r=await fetch('/api/playback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entryId:entry.id})});const d=await r.json() as any;if(!r.ok){if(active)setNeedSignIn(r.status===401);throw new Error(d.error)}sid.current=d.id;if(active){setToken(d.id);setMessage('');setNeedSignIn(false)}else await report(true)}catch(e){if(active)setMessage((e as Error).message)}finally{starting.current=false}}start();return()=>{active=false}},[entry.id,retry,signedIn]);
 useEffect(()=>{const timer=setInterval(()=>report(),15000);const lost=()=>{wantPlay.current=!!ref.current&&!ref.current.paused;setOffline(true);setMessage('कनेक्शन नहीं है। लौटने पर वीडियो जारी करने की कोशिश होगी।')};const restored=()=>{setOffline(false);if(wantPlay.current){snapshot();setToken('');setRetry(n=>n+1)}};const hidden=()=>{if(document.visibilityState==='hidden')report()};window.addEventListener('offline',lost);window.addEventListener('online',restored);document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);window.removeEventListener('offline',lost);window.removeEventListener('online',restored);document.removeEventListener('visibilitychange',hidden);pendingRelease=report(true)}},[]);
 return <><label className="flex items-center gap-3"><Switch checked={saver} onCheckedChange={v=>{setSaver(v);try{localStorage.setItem('ott-data-saver',v?'1':'0')}catch{}}}/>Data Saver {saver?'ON':'OFF'}</label><p className="subtle">Data Saver में वीडियो टैप करने पर लोड होगी। क्वालिटी मूल वीडियो की रहेगी।</p>{token?<video ref={ref} key={token} src={`/api/media/${entry.id}?session=${token}`} controls autoPlay={!saver||wantPlay.current} playsInline preload={saver?'none':'metadata'} onLoadedMetadata={e=>{e.currentTarget.currentTime=Math.min(position.current,e.currentTarget.duration||position.current)}} onPlaying={()=>{setBuffering(false);setMessage('');wantPlay.current=true;lastTick.current=performance.now();lastPosition.current=ref.current?.currentTime||0}} onWaiting={()=>setBuffering(true)} onStalled={()=>setBuffering(true)} onSeeking={()=>{lastTick.current=0}} onTimeUpdate={e=>{const v=e.currentTarget,now=performance.now(),elapsed=(now-lastTick.current)/1000,advance=v.currentTime-lastPosition.current;if(lastTick.current&&!v.paused&&!v.seeking&&advance>0&&advance<elapsed*3+1)watched.current+=Math.min(elapsed,advance,2);lastTick.current=now;lastPosition.current=v.currentTime;position.current=Math.floor(v.currentTime);duration.current=Number.isFinite(v.duration)?Math.ceil(v.duration):0}} onPause={()=>{if(navigator.onLine)wantPlay.current=false;report()}} onEnded={()=>{wantPlay.current=false;report()}} onError={()=>setMessage('वीडियो लोड नहीं हुई। कनेक्शन लौटने पर फिर कोशिश करें।')}/>:<p>वीडियो तैयार करें या फिर कोशिश करें।</p>}{buffering&&!offline&&token&&<p role="status">वीडियो लोड हो रही है… कमजोर इंटरनेट पर थोड़ा इंतज़ार करें।</p>}{message&&<p role="status" className="notice">{message}</p>}{needSignIn?<Button asChild><a href="/signin-with-chatgpt?return_to=/" target="_top">साइन इन करें</a></Button>:<Button variant="outline" disabled={offline} onClick={()=>{snapshot();wantPlay.current=true;setToken('');setRetry(n=>n+1)}}>फिर कोशिश करें / जारी रखें</Button>}{position.current>0&&<Button variant="outline" onClick={()=>{position.current=0;if(ref.current)ref.current.currentTime=0}}>शुरू से देखें</Button>}{entry.description&&<p>{entry.description}</p>}{!signedIn&&<p className="subtle">अगली बार वहीं से देखने के लिए साइन इन करें।</p>}{next&&<Button onClick={()=>onNext(next)}>अगला वीडियो · {next.song}</Button>}<p className="subtle">देखने का समय और छोड़ी गई जगह सेवा के आँकड़ों में दर्ज होते हैं।</p></>
}
