'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
type Movie={id:string;song:string;content_type:string};
type Contract={entry_id:string;title:string;producer_name:string;producer_email?:string;enabled:number;producer_percent:number;terms:string;gross_paise:number;deductions_paise:number;earned_paise:number;platform_paise?:number;paid_paise:number;sales_count:number};
type Ledger={id:string;entry_id:string;kind:string;gross_paise:number;deductions_paise:number;producer_paise:number;payout_paise:number;producer_percent:number;occurred_at:number;reference?:string;note?:string};
type Report={isAdmin:boolean;contracts:Contract[];ledger:Ledger[]};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
const date=(n:number)=>new Intl.DateTimeFormat('hi-IN',{dateStyle:'medium',timeZone:'Asia/Kolkata'}).format(n);
async function request(path:string,options?:RequestInit){const res=await fetch(path,{...options,cache:'no-store'});const data=await res.json() as Report & {error?:string};if(!res.ok)throw new Error(data.error||'रिपोर्ट नहीं खुली।');return data}
function Stats({contract:c,admin=false}:{contract:Contract;admin?:boolean}){return <div className="revenue-stats">{[['बिक्री',String(c.sales_count)],['कुल बिक्री',money(c.gross_paise)],['कटौतियाँ',money(c.deductions_paise)],['निर्माता की कमाई',money(c.earned_paise)],['भुगतान दर्ज',money(c.paid_paise)],['बकाया',money(c.earned_paise-c.paid_paise)],...(admin?[['OTT का हिस्सा',money(c.platform_paise||0)]]:[])].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
function History({rows,admin=false}:{rows:Ledger[];admin?:boolean}){return rows.length?<div className="revenue-table"><table><caption>दर्ज बिक्री और भुगतान</caption><thead><tr><th>तारीख</th><th>प्रकार</th><th>बिक्री</th><th>कटौती</th><th>निर्माता का हिस्सा</th><th>भुगतान</th>{admin&&<><th>संदर्भ</th><th>विवरण</th></>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.occurred_at)}</td><td>{r.kind==='sale'?'बिक्री':'भुगतान'}</td><td>{money(r.gross_paise)}</td><td>{money(r.deductions_paise)}</td><td>{r.kind==='sale'?`${money(r.producer_paise)} (${r.producer_percent}%)`:'—'}</td><td>{money(r.payout_paise)}</td>{admin&&<><td>{r.reference}</td><td>{r.note||'—'}</td></>}</tr>)}</tbody></table></div>:<p className="notice">अभी कोई बिक्री या भुगतान दर्ज नहीं है।</p>}
export default function RevenuePanel({admin=false,movies=[]}:{admin?:boolean;movies?:Movie[]}){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{const data=await request('/api/revenue');setReport(data);setError('')},[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function reload(){try{await load()}catch(e){setError((e as Error).message)}}
 if(error&&!report)return <div className="notice error" role="alert">{error} <Button variant="outline" onClick={reload}>फिर कोशिश करें</Button></div>;
 if(!report)return <p className="subtle" role="status">खाता लोड हो रहा है…</p>;
 if(!admin&&!report.contracts.length)return null;
 const contract=report.contracts.find(c=>c.entry_id===selected);
 return <section className="revenue-panel"><div className="event-heading"><div><h2>Revenue Sharing</h2><p className="subtle">{admin?'चुनिंदा फिल्मों के निर्माता और कमाई का प्रबंधन':'आपकी फिल्मों की कमाई और भुगतान'}</p></div><Button variant="outline" onClick={reload}>रिपोर्ट अपडेट करें</Button></div>
 <p className="notice">{admin?'यह दर्ज बिक्री और भुगतान का हिसाब है। ऑनलाइन rental checkout और स्वतः बैंक भुगतान अभी जुड़े नहीं हैं। केवल प्राप्त बिक्री और किए हुए भुगतान दर्ज करें।':'यह Admin द्वारा दर्ज बिक्री और भुगतान की रिपोर्ट है। भुगतान रिकॉर्ड अपने बैंक खाते से मिलाएँ।'}</p>
 {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {admin&&report.isAdmin&&<><div className="field"><label htmlFor="revenue-movie">Revenue Sharing के लिए फिल्म चुनें</label><select id="revenue-movie" value={selected} onChange={e=>{setSelected(e.target.value);setNotice('')}}><option value="">फिल्म चुनें</option>{movies.filter(m=>m.content_type==='movie').map(m=><option key={m.id} value={m.id}>{m.song}{report.contracts.some(c=>c.entry_id===m.id)?' · Sharing सेट है':''}</option>)}</select></div>{!movies.some(m=>m.content_type==='movie')&&<p className="subtle">पहले फिल्म अपलोड और प्रकाशित करें।</p>}{selected&&<ContractForm key={selected+'-'+(contract?.producer_email||'')+'-'+(contract?.producer_percent||0)+'-'+(contract?.enabled||0)} id={selected} contract={contract} onSaved={async()=>{await load();setNotice('फिल्म की Revenue Sharing सेटिंग सेव हो गई।')}}/>}{contract&&<LedgerForm key={selected} contract={contract} onSaved={async()=>{await load();setNotice('वास्तविक लेनदेन का रिकॉर्ड सेव हो गया।')}}/>}</>}
 {!report.contracts.length&&admin&&<p className="subtle">किसी फिल्म पर Revenue Sharing चालू नहीं की गई है। आपकी बाकी फिल्में इस योजना में अपने-आप शामिल नहीं होंगी।</p>}
 {report.contracts.map(c=><article key={c.entry_id} className="revenue-film"><h3>{c.title}</h3><p>{c.producer_name} · निर्माता {c.producer_percent}%{admin?` / OTT ${100-c.producer_percent}%`:''}{admin&&<span className="badge">{c.enabled?'Sharing ON':'Sharing OFF'}</span>}</p>{admin&&<p className="subtle">लॉगिन: {c.producer_email}</p>}<Stats contract={c} admin={admin}/>{c.terms&&<details><summary>सहमत शर्तें</summary><p className="preserve-lines">{c.terms}</p></details>}<History rows={report.ledger.filter(r=>r.entry_id===c.entry_id)} admin={admin}/></article>)}
 </section>
}
function ContractForm({id,contract:c,onSaved}:{id:string;contract?:Contract;onSaved:()=>Promise<void>}){
 const [enabled,setEnabled]=useState(!!c?.enabled),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await request('/api/revenue',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({entryId:id,enabled,producerName:f.get('name'),producerEmail:f.get('email'),producerPercent:Number(f.get('percent')),terms:f.get('terms')})});await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit} className="revenue-form"><h3>निर्माता और हिस्सेदारी</h3><fieldset disabled={busy}><label className="revenue-toggle"><Switch checked={enabled} onCheckedChange={setEnabled} aria-label="इस फिल्म पर Revenue Sharing"/><span>Revenue Sharing {enabled?'ON':'OFF'}</span></label><p className="subtle">ON करने पर नीचे दिए ईमेल से लॉगिन करने वाले निर्माता को अपनी फिल्म का हिसाब दिखेगा। OFF करने पर उसकी रिपोर्ट छिपेगी; पुराना हिसाब Admin के पास रहेगा।</p><div className="form-grid"><div className="field"><label htmlFor="producer-name">निर्माता का नाम</label><Input id="producer-name" name="name" required maxLength={150} defaultValue={c?.producer_name||''}/></div><div className="field"><label htmlFor="producer-email">निर्माता का ChatGPT लॉगिन ईमेल</label><Input id="producer-email" name="email" type="email" required maxLength={254} defaultValue={c?.producer_email||''}/></div></div><div className="field"><label htmlFor="producer-percent">निर्माता का हिस्सा (%)</label><Input id="producer-percent" name="percent" type="number" required min={1} max={99} step={1} defaultValue={c?.producer_percent??70}/><small className="subtle">शेष हिस्सा Gondwana OTT का। कटौतियों के बाद बँटवारा होगा। नई दर केवल आगे दर्ज बिक्री पर लागू होगी।</small></div><div className="field"><label htmlFor="revenue-terms">सहमत शर्तें और अनुमत कटौतियाँ</label><textarea id="revenue-terms" name="terms" maxLength={3000} rows={3} defaultValue={c?.terms||''} placeholder="हिस्सेदारी, कटौतियाँ, भुगतान का समय और अवधि"/></div>{error&&<p className="notice error" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy?'सेव हो रहा है…':'Sharing सेटिंग सेव करें'}</Button></fieldset></form>
}
function LedgerForm({contract:c,onSaved}:{contract:Contract;onSaved:()=>Promise<void>}){
 const [kind,setKind]=useState('sale'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const paise=(value:FormDataEntryValue|null)=>{const raw=String(value??'0');if(!/^\d+(\.\d{1,2})?$/.test(raw))throw new Error('रकम रुपये में अधिकतम दो दशमलव के साथ भरें।');return Math.round(Number(raw)*100)};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setError('');try{await request('/api/revenue/ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId,entryId:c.entry_id,kind,grossPaise:kind==='sale'?paise(f.get('gross')):0,deductionsPaise:kind==='sale'?paise(f.get('deductions')):0,payoutPaise:kind==='payout'?paise(f.get('payout')):0,reference:f.get('reference'),note:f.get('note'),occurredAt:Date.parse(String(f.get('date'))+'T00:00:00+05:30')})});setRequestId(crypto.randomUUID());form.reset();await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form className="revenue-form" onSubmit={submit}><h3>वास्तविक बिक्री / भुगतान दर्ज करें</h3><p className="subtle">यह बैंक में पैसे भेजने का विकल्प नहीं है। भुगतान करने के बाद उसका संदर्भ यहाँ दर्ज करें। एक संदर्भ दोबारा दर्ज नहीं होगा।</p><fieldset disabled={busy}><div className="field"><label htmlFor="ledger-kind">रिकॉर्ड का प्रकार</label><select id="ledger-kind" value={kind} onChange={e=>{setKind(e.target.value);setRequestId(crypto.randomUUID())}}><option value="sale">प्राप्त फिल्म किराया / बिक्री</option><option value="payout">निर्माता को किया हुआ भुगतान</option></select></div><div className="form-grid">{kind==='sale'?<><div className="field"><label htmlFor="ledger-gross">प्राप्त बिक्री (₹)</label><Input id="ledger-gross" name="gross" type="number" min="0.01" max="1000000" step="0.01" required/></div><div className="field"><label htmlFor="ledger-deductions">सहमत कटौतियाँ (₹)</label><Input id="ledger-deductions" name="deductions" type="number" min="0" max="1000000" step="0.01" required defaultValue="0"/></div></>:<div className="field"><label htmlFor="ledger-payout">किया गया भुगतान (₹)</label><Input id="ledger-payout" name="payout" type="number" min="0.01" max={(c.earned_paise-c.paid_paise)/100} step="0.01" required/><small className="subtle">बकाया: {money(c.earned_paise-c.paid_paise)}</small></div>}<div className="field"><label htmlFor="ledger-date">लेनदेन तारीख (IST)</label><Input id="ledger-date" name="date" type="date" required/></div><div className="field"><label htmlFor="ledger-reference">अलग receipt / UTR संदर्भ</label><Input id="ledger-reference" name="reference" required maxLength={120}/></div></div><div className="field"><label htmlFor="ledger-note">कटौतियों / भुगतान का विवरण (Admin)</label><textarea id="ledger-note" name="note" rows={2} maxLength={1500}/></div><label className="revenue-toggle"><input type="checkbox" required/>मैंने रकम, तारीख और संदर्भ जाँच लिया है।</label>{error&&<p className="notice error" role="alert">{error}</p>}{kind==='sale'&&!c.enabled&&<p className="notice">नई बिक्री दर्ज करने के लिए Sharing ON करें।</p>}<Button type="submit" disabled={busy||(kind==='sale'&&!c.enabled)}>{busy?'सेव हो रहा है…':'लेनदेन दर्ज करें'}</Button></fieldset></form>
}
