import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler'));
const {Miniflare}=wranglerRequire('miniflare');
const root=new URL('../dist/server/',import.meta.url).pathname;const files=(await readdir(root,{recursive:true})).filter(x=>/\.m?js$/.test(x)&&x!=='index.js');const modules=['index.js',...files].map(x=>({type:'ESModule',path:root+x}));
const mf=new Miniflare({modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{OWNER_EMAIL:'organizer@example.test',PUBLIC_ORIGIN:'https://test.invalid'},cf:false});
try{
 const db=await mf.getD1Database('DB');for(const migration of (await readdir(new URL('../drizzle/',import.meta.url))).filter(n=>n.endsWith('.sql')).sort()){const sql=await readFile(new URL('../drizzle/'+migration,import.meta.url),'utf8');for(const statement of sql.split('--> statement-breakpoint'))if(statement.trim())await db.prepare(statement).run();}
 const owner={'oai-authenticated-user-id':'test-owner','oai-authenticated-user-email':'organizer@example.test'},viewer={'oai-authenticated-user-id':'test-viewer','oai-authenticated-user-email':'viewer@example.test'};
 const send=(path,options={})=>mf.dispatchFetch('https://test.invalid'+path,options);
 const post=(path,body,user=owner)=>send(path,{method:'POST',headers:{Origin:'https://test.invalid','Content-Type':'application/json',...user},body:JSON.stringify(body)});
 let res=await send('/',{headers:owner});assert.equal(res.status,200);assert.match(await res.text(),/GONDWANA/);res=await send('/api/entries');assert.equal(res.status,200);assert.deepEqual((await res.json()).entries,[]);
 res=await send('/api/session',{headers:owner});const session=await res.json();assert.equal(session.isAdmin,true);
 res=await send('/api/offers',{headers:owner});assert.equal((await res.json()).gateway.ready,false);res=await post('/api/orders',{offerId:crypto.randomUUID(),requestId:crypto.randomUUID()},viewer);assert.equal(res.status,503,'no checkout without configured live gateway');
 const payload={singer:'Test Singer',song:'Local transport test',city:'Test',mime:'video/mp4',size:8*1024*1024+64};
 res=await post('/api/uploads',payload,{});assert.equal(res.status,401);
 res=await post('/api/uploads',payload,viewer);assert.equal(res.status,403);
 res=await send('/api/uploads',{method:'POST',headers:{...owner,Origin:'https://evil.invalid','Content-Type':'application/json'},body:JSON.stringify(payload)});assert.equal(res.status,403);
 res=await post('/api/uploads',payload);assert.equal(res.status,201);const upload=await res.json();
 res=await send(`/api/media/${upload.id}`);assert.equal(res.status,404);
 res=await post(`/api/uploads/${upload.id}/complete`,{});assert.equal(res.status,409);
 const bytes=new Uint8Array(payload.size);bytes.set([0,0,0,24,102,116,121,112,105,115,111,109]);
 for(let part=1;part<=2;part++){const body=bytes.slice((part-1)*upload.chunkSize,Math.min(part*upload.chunkSize,bytes.length));res=await send(`/api/uploads/${upload.id}/part?part=${part}`,{method:'PUT',headers:{...owner,Origin:'https://test.invalid','Content-Length':String(body.length)},body});assert.equal(res.status,200,await res.text());}
 res=await post(`/api/uploads/${upload.id}/complete`,{});assert.equal(res.status,200,await res.text());
 res=await post(`/api/uploads/${upload.id}/complete`,{});assert.equal(res.status,200);
 res=await send(`/api/media/${upload.id}`,{headers:{Range:'bytes=4-7'}});assert.equal(res.status,206);assert.equal(res.headers.get('content-range'),`bytes 4-7/${bytes.length}`);assert.equal(await res.text(),'ftyp');
 res=await send(`/api/media/${upload.id}`,{headers:{Range:'bytes=99999999-'}});assert.equal(res.status,416);
 res=await post(`/api/entries/${upload.id}/vote`,{},{});assert.equal(res.status,401);
 res=await post(`/api/entries/${upload.id}/vote`,{},viewer);assert.equal(res.status,403);
 const fixtureEvent=crypto.randomUUID();await db.prepare('INSERT INTO events (id,name,type,starts_at,ends_at,created_by,created_at,voting_enabled) VALUES (?,?,?,?,?,?,?,1)').bind(fixtureEvent,'Earlier singing event','singing',Date.now()-10000,Date.now()+3600000,'test-owner',1).run();await db.prepare('UPDATE performances SET event_id=? WHERE id=?').bind(fixtureEvent,upload.id).run();
 const votes=await Promise.all(Array.from({length:5},()=>post(`/api/entries/${upload.id}/vote`,{},viewer)));for(const vote of votes)assert.equal(vote.status,200);
 res=await send('/api/entries',{headers:viewer});const list=(await res.json()).entries;assert.equal(list.length,1);assert.equal(Object.hasOwn(list[0],'votes'),false);assert.equal(list[0].voted,1);
 res=await post(`/api/entries/${upload.id}/vote`,{},owner);assert.equal(res.status,200);assert.equal((await res.json()).votes,2);
 assert.equal(list[0].content_type,'singing');
 for(const invalid of [{contentType:'bad'},{contentType:'movie',genre:'bad'},{contentType:'series',genre:'ड्रामा',seriesTitle:'Test Series',season:0,episode:1}]){res=await post('/api/uploads',{...payload,...invalid});assert.equal(res.status,400);}
 for(const contentType of ['dance','movie','series']){
  const metadata={...payload,size:64,contentType,genre:'ड्रामा',seriesTitle:'Test Series',season:2,episode:3};
  res=await post('/api/uploads',metadata,viewer);assert.equal(res.status,403);
  res=await post('/api/uploads',metadata);assert.equal(res.status,201);const item=await res.json();
  const body=bytes.slice(0,64);res=await send(`/api/uploads/${item.id}/part?part=1`,{method:'PUT',headers:{...owner,Origin:'https://test.invalid','Content-Length':'64'},body});assert.equal(res.status,200);
  res=await post(`/api/uploads/${item.id}/complete`,{});assert.equal(res.status,200);
  res=await post(`/api/entries/${item.id}/vote`,{},viewer);assert.equal(res.status,contentType==='dance'?403:404);
  if(contentType==='dance'){res=await post(`/api/entries/${item.id}/vote`,{},viewer);assert.equal(Object.hasOwn(await res.json(),'votes'),false);}
  res=await send('/api/entries',{headers:viewer});const record=(await res.json()).entries.find(e=>e.id===item.id);assert.equal(record.content_type,contentType);assert.equal(Object.hasOwn(record,'votes'),false);
  if(contentType!=='dance')assert.equal(record.genre,'ड्रामा');
  if(contentType==='series'){assert.equal(record.series_title,'Test Series');assert.equal(record.season,2);assert.equal(record.episode,3);}
 }
 const makeEvent=async(fields={},user=owner,poster=false)=>{const body=new FormData();for(const [key,value] of Object.entries({name:'Test Dance Event',type:'dance',description:'Test description',rules:'Test rules',startsAt:Date.now()+60000,endsAt:Date.now()+3600000,...fields}))body.set(key,String(value));if(poster)body.set('poster',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'poster.png');const request=new Request('https://test.invalid/api/events',{method:'POST',body});return send('/api/events',{method:'POST',headers:{...user,Origin:'https://test.invalid','Content-Type':request.headers.get('content-type')},body:await request.arrayBuffer()})};
 res=await makeEvent({},viewer);assert.equal(res.status,403);res=await makeEvent({},{});assert.equal(res.status,401);
 res=await makeEvent({endsAt:1});assert.equal(res.status,400);res=await makeEvent({type:'movie'});assert.equal(res.status,400);
 res=await makeEvent({},owner,true);assert.equal(res.status,201,await res.clone().text());const competition=await res.json();
 res=await send(`/api/events/${competition.id}/poster`);assert.equal(res.status,200);assert.equal(res.headers.get('content-type'),'image/png');
 res=await send('/api/events');const eventList=(await res.json()).events;assert.equal(eventList.length,2);assert.equal(eventList[0].voting_enabled,0);assert.equal(eventList[0].rules,'Test rules');assert.equal(eventList[0].has_poster,1);
 res=await post('/api/uploads',{...payload,contentType:'singing',eventId:competition.id});assert.equal(res.status,400);
 res=await post('/api/uploads',{...payload,size:64,contentType:'dance',eventId:competition.id});assert.equal(res.status,201);const contestant=await res.json();
 res=await send(`/api/uploads/${contestant.id}/part?part=1`,{method:'PUT',headers:{...owner,Origin:'https://test.invalid','Content-Length':'64'},body:bytes.slice(0,64)});assert.equal(res.status,200);
 res=await post(`/api/uploads/${contestant.id}/complete`,{});assert.equal(res.status,200);
 res=await post(`/api/entries/${contestant.id}/vote`,{},viewer);assert.equal(res.status,403);
 const voting=(enabled,user=owner,origin='https://test.invalid')=>send(`/api/events/${competition.id}/voting`,{method:'PATCH',headers:{...user,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({enabled})});
 res=await voting(true,viewer);assert.equal(res.status,403);res=await voting(true,{});assert.equal(res.status,401);res=await voting(true,owner,'https://evil.invalid');assert.equal(res.status,403);res=await voting('yes');assert.equal(res.status,400);
 res=await voting(true);assert.equal(res.status,200);res=await post(`/api/entries/${contestant.id}/vote`,{},viewer);assert.equal(res.status,403);
 res=await voting(false);assert.equal(res.status,200);
 await db.prepare('UPDATE events SET starts_at=? WHERE id=?').bind(Date.now()-10000,competition.id).run();
 res=await post(`/api/entries/${contestant.id}/vote`,{},viewer);assert.equal(res.status,403);
 res=await voting(true);assert.equal(res.status,200);
 res=await post(`/api/entries/${contestant.id}/vote`,{},viewer);assert.equal(res.status,200);assert.equal(Object.hasOwn(await res.json(),'votes'),false);
 res=await post(`/api/entries/${contestant.id}/vote`,{},viewer);assert.equal(Object.hasOwn(await res.json(),'votes'),false);
 res=await voting(false);assert.equal(res.status,200);res=await post(`/api/entries/${contestant.id}/vote`,{},owner);assert.equal(res.status,403);
 assert.equal((await db.prepare('SELECT COUNT(*) AS total FROM votes WHERE entry_id=?').bind(contestant.id).first()).total,1);
 res=await voting(true);assert.equal(res.status,200);
 await db.prepare('UPDATE events SET ends_at=? WHERE id=?').bind(Date.now()-1000,competition.id).run();
 res=await post(`/api/entries/${contestant.id}/vote`,{},owner);assert.equal(res.status,403);
 res=await post('/api/uploads',{...payload,contentType:'dance',eventId:competition.id});assert.equal(res.status,400);
 res=await send('/api/entries',{headers:owner});const records=(await res.json()).entries;assert.equal(records.find(e=>e.id===contestant.id).event_id,competition.id);assert.equal(records.find(e=>e.id===contestant.id).votes,1);assert.equal(records.find(e=>e.id===upload.id).votes,2);
 for(const user of [{},viewer]){res=await send('/api/entries',{headers:user});const publicEntries=(await res.json()).entries;assert.ok(publicEntries.length>0);for(const entry of publicEntries)assert.equal(Object.hasOwn(entry,'votes'),false);}
 res=await send('/api/entries',{headers:viewer});assert.equal((await res.json()).entries.find(e=>e.id===upload.id).voted,1);
 res=await send('/api/entries',{headers:owner});assert.equal((await res.json()).entries.find(e=>e.id===upload.id).votes,2);
 res=await post(`/api/entries/${upload.id}/vote`,{},viewer);const privateVote=await res.json();assert.equal(Object.hasOwn(privateVote,'votes'),false);assert.equal(privateVote.voted,1);
 // Revenue Sharing: opt-in, account isolation, immutable sale rates and bounded payouts.
 const producerA={'oai-authenticated-user-id':'producer-a','oai-authenticated-user-email':'producer-a@example.test'},producerB={'oai-authenticated-user-id':'producer-b','oai-authenticated-user-email':'producer-b@example.test'};
 const movieId=records.find(e=>e.content_type==='movie').id;
 const movieB=crypto.randomUUID();await db.prepare("INSERT INTO performances (id,singer,song,content_type,object_key,mime,size,upload_id,status,created_by,created_at,published_at) VALUES (?,?,?,'movie',?,'video/mp4',64,?,'published',?,?,?)").bind(movieB,'Other Producer','Other Film','test-other',crypto.randomUUID(),'test-owner',Date.now(),Date.now()).run();
 const contractBody={entryId:movieId,producerName:'Producer A',producerEmail:'Producer-A@example.test',producerPercent:70,enabled:true,terms:'Agreed deductions; monthly payment'};
 const setContract=(body,user=owner)=>send('/api/revenue',{method:'PUT',headers:{...user,Origin:'https://test.invalid','Content-Type':'application/json'},body:JSON.stringify(body)});
 res=await send('/api/revenue');assert.equal(res.status,401);
 res=await setContract(contractBody,viewer);assert.equal(res.status,403);
 res=await setContract({...contractBody,entryId:upload.id});assert.equal(res.status,404);
 res=await setContract({...contractBody,producerPercent:101});assert.equal(res.status,400);
 res=await setContract(contractBody);assert.equal(res.status,200,await res.clone().text());
 res=await setContract({...contractBody,entryId:movieB,producerName:'Producer B',producerEmail:'producer-b@example.test'});assert.equal(res.status,200);
 res=await send('/api/revenue',{headers:viewer});assert.deepEqual((await res.json()).contracts,[]);
 res=await send('/api/revenue',{headers:producerA});let revenue=await res.json();assert.equal(revenue.contracts.length,1);assert.equal(revenue.contracts[0].entry_id,movieId);assert.equal(revenue.contracts[0].earned_paise,0);assert.equal(Object.hasOwn(revenue.contracts[0],'producer_email'),false);
 const sale={id:crypto.randomUUID(),entryId:movieId,kind:'sale',grossPaise:9900,deductionsPaise:900,payoutPaise:0,reference:'sale-001',note:'Agreed payment and delivery costs',occurredAt:Date.now()-1000};
 res=await post('/api/revenue/ledger',sale,producerA);assert.equal(res.status,403);
 res=await post('/api/revenue/ledger',{...sale,deductionsPaise:10000});assert.equal(res.status,400);
 res=await post('/api/revenue/ledger',sale);assert.equal(res.status,201,await res.clone().text());
 res=await post('/api/revenue/ledger',sale);assert.equal(res.status,200);
 res=await post('/api/revenue/ledger',{...sale,id:crypto.randomUUID()});assert.equal(res.status,409);
 res=await setContract({...contractBody,producerEmail:'producer-b@example.test'});assert.equal(res.status,409);
 res=await setContract({...contractBody,producerPercent:80});assert.equal(res.status,200);
 res=await send('/api/revenue',{headers:producerA});revenue=await res.json();assert.equal(revenue.contracts[0].earned_paise,6300);assert.equal(revenue.ledger[0].producer_percent,70);assert.equal(Object.hasOwn(revenue.ledger[0],'reference'),false);assert.equal(Object.hasOwn(revenue.ledger[0],'note'),false);
 res=await send('/api/revenue',{headers:producerB});revenue=await res.json();assert.equal(revenue.contracts.length,1);assert.equal(revenue.contracts[0].entry_id,movieB);assert.equal(revenue.ledger.length,0);
 const payout={...sale,id:crypto.randomUUID(),kind:'payout',grossPaise:0,deductionsPaise:0,payoutPaise:6400,reference:'utr-001',note:'Bank transfer completed'};
 res=await post('/api/revenue/ledger',payout);assert.equal(res.status,409);
 const races=await Promise.all([post('/api/revenue/ledger',{...payout,payoutPaise:4000}),post('/api/revenue/ledger',{...payout,id:crypto.randomUUID(),reference:'utr-002',payoutPaise:4000})]);assert.deepEqual(races.map(r=>r.status).sort(),[201,409]);
 res=await setContract({...contractBody,enabled:false});assert.equal(res.status,200);
 res=await send('/api/revenue',{headers:producerA});revenue=await res.json();assert.equal(revenue.contracts.length,0);assert.equal(revenue.ledger.length,0);
 res=await post('/api/revenue/ledger',{...sale,id:crypto.randomUUID(),reference:'sale-off'});assert.equal(res.status,409);
 res=await send('/api/revenue',{headers:owner});revenue=await res.json();assert.equal(revenue.contracts.length,2);const movieReport=revenue.contracts.find(c=>c.entry_id===movieId);assert.equal(movieReport.earned_paise,6300);assert.equal(movieReport.paid_paise,4000);assert.equal(movieReport.platform_paise,2700);assert.ok(revenue.ledger.every(l=>l.reference));
 console.log('PASS: optional Revenue Sharing, producer isolation, admin-only writes, disabled visibility, exact 70/30 calculations, preserved historical rates, duplicate prevention and concurrent payout limit.');
 const picture=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII=','base64');
 const art=(id,kind,user=owner,body=picture)=>send(`/api/entries/${id}/artwork?kind=${kind}`,{method:'PUT',headers:{...user,Origin:'https://test.invalid','Content-Type':'image/png'},body});
 res=await art(upload.id,'poster',viewer);assert.equal(res.status,403);
 res=await art(upload.id,'poster',{});assert.equal(res.status,401);
 res=await art(upload.id,'invalid');assert.equal(res.status,400);
 res=await art(upload.id,'poster',owner,Buffer.from('<svg/>'));assert.equal(res.status,400);
 res=await art(upload.id,'poster',owner,Buffer.alloc(2*1024*1024+1));assert.equal(res.status,413);
 for(const kind of ['poster','thumbnail']){res=await art(upload.id,kind);assert.equal(res.status,200,await res.text());res=await send(`/api/entries/${upload.id}/artwork?kind=${kind}`);assert.equal(res.status,200);assert.equal(res.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await res.arrayBuffer()),picture);}
 res=await send('/api/entries');const artworkRecord=(await res.json()).entries.find(e=>e.id===upload.id);assert.equal(artworkRecord.has_poster,1);assert.equal(artworkRecord.has_thumbnail,1);assert.equal(Object.hasOwn(artworkRecord,'votes'),false);
 res=await post('/api/uploads',{...payload,size:64});assert.equal(res.status,201);const pendingArt=await res.json();res=await art(pendingArt.id,'poster');assert.equal(res.status,200);
 res=await send(`/api/entries/${pendingArt.id}/artwork?kind=poster`);assert.equal(res.status,404);
 res=await send(`/api/entries/${pendingArt.id}/artwork?kind=poster`,{headers:owner});assert.equal(res.status,200);
 res=await art(upload.id,'poster');assert.equal(res.status,200);
 console.log('PASS: admin-only poster/thumbnail upload, format and size validation, durable artwork retrieval and replacement, unpublished artwork protected, public vote totals hidden, existing events/voting/media workflows. Isolated test storage.');
 const episodePatch=(body,user=owner)=>send('/api/episodes',{method:'PATCH',headers:{...user,Origin:'https://test.invalid','Content-Type':'application/json'},body:JSON.stringify(body)});
 const episodePayload={eventId:fixtureEvent,episode:1,title:'Auditions',description:'First round'};
 res=await post('/api/episodes',episodePayload,viewer);assert.equal(res.status,403);
 res=await post('/api/episodes',episodePayload,{});assert.equal(res.status,401);
 res=await post('/api/episodes',episodePayload);assert.equal(res.status,201);const eventEpisode=await res.json();
 res=await post('/api/episodes',episodePayload);assert.equal(res.status,409);
 res=await episodePatch({action:'mode',eventId:fixtureEvent,enabled:true},viewer);assert.equal(res.status,403);
 res=await episodePatch({action:'mode',eventId:fixtureEvent,enabled:true});assert.equal(res.status,200);
 res=await post(`/api/entries/${upload.id}/vote`,{},owner);assert.equal(res.status,403);
 res=await post('/api/uploads',{...payload,eventId:fixtureEvent});assert.equal(res.status,400);
 res=await episodePatch({action:'assign',entryId:upload.id,id:eventEpisode.id});assert.equal(res.status,200);
 res=await post(`/api/entries/${upload.id}/vote`,{},owner);assert.equal(res.status,403);
 res=await episodePatch({action:'voting',id:eventEpisode.id,enabled:true});assert.equal(res.status,200);
 res=await post(`/api/entries/${upload.id}/vote`,{},owner);assert.equal(res.status,200);
 await db.prepare('UPDATE performances SET vote_eligible=0 WHERE id=?').bind(upload.id).run();
 res=await post(`/api/entries/${upload.id}/vote`,{},owner);assert.equal(res.status,403);
 await db.prepare('UPDATE performances SET vote_eligible=1 WHERE id=?').bind(upload.id).run();
 res=await episodePatch({action:'voting',id:eventEpisode.id,enabled:false});assert.equal(res.status,200);
 res=await post(`/api/entries/${upload.id}/vote`,{},owner);assert.equal(res.status,403);
 res=await episodePatch({action:'assign',entryId:contestant.id,id:eventEpisode.id});assert.equal(res.status,400);
 const seriesPayload={seriesTitle:'Test Series',genre:'ड्रामा',season:2,episode:3,title:'Third episode'};
 res=await post('/api/episodes',seriesPayload);assert.equal(res.status,201);const seriesEpisode=await res.json();
 const seriesRecord=records.find(e=>e.content_type==='series');
 res=await episodePatch({action:'assign',entryId:seriesRecord.id,id:seriesEpisode.id});assert.equal(res.status,200);
 res=await episodePatch({action:'voting',id:seriesEpisode.id,enabled:true});assert.equal(res.status,404);
 res=await post('/api/uploads',{...payload,size:64,contentType:'series',seriesTitle:'Wrong Series',genre:'ड्रामा',season:2,episode:3,episodeGroupId:seriesEpisode.id});assert.equal(res.status,400);
 res=await post('/api/uploads',{...payload,size:64,eventId:fixtureEvent,episodeGroupId:eventEpisode.id,voteEligible:false,description:'Full program',durationSeconds:300});assert.equal(res.status,201);const program=await res.json();
 const programRow=await db.prepare('SELECT episode_group_id,vote_eligible,duration_seconds FROM performances WHERE id=?').bind(program.id).first();assert.equal(programRow.episode_group_id,eventEpisode.id);assert.equal(programRow.vote_eligible,0);assert.equal(programRow.duration_seconds,300);
 const progressPut=(id,body,user=viewer)=>send(`/api/progress/${id}`,{method:'PUT',headers:{...user,Origin:'https://test.invalid','Content-Type':'application/json'},body:JSON.stringify(body)});
 res=await progressPut(seriesRecord.id,{position:42,duration:100,completed:false},{});assert.equal(res.status,401);
 res=await progressPut(seriesRecord.id,{position:142,duration:100,completed:false});assert.equal(res.status,400);
 res=await progressPut(program.id,{position:42,duration:100,completed:false});assert.equal(res.status,404);
 res=await progressPut(seriesRecord.id,{position:42,duration:100,completed:false});assert.equal(res.status,200);
 res=await send(`/api/progress/${seriesRecord.id}`,{headers:viewer});assert.equal((await res.json()).progress.position_seconds,42);
 res=await send(`/api/progress/${seriesRecord.id}`,{headers:owner});assert.equal((await res.json()).progress,null);
 res=await progressPut(seriesRecord.id,{position:100,duration:100,completed:true});assert.equal(res.status,200);
 res=await send(`/api/progress/${seriesRecord.id}`,{headers:viewer});assert.equal((await res.json()).progress.completed,1);
 res=await send('/api/episodes');const episodeList=(await res.json()).episodes;assert.equal(episodeList.length,2);assert.equal(episodeList.find(e=>e.id===eventEpisode.id).voting_enabled,0);
 console.log('PASS: episode authorization, unique numbering, event grouping, episode voting gates, full-program vote protection, series isolation, durable per-user resume and completion.');
 res=await makeEvent({typeLabel:'  कबड्डी प्रतियोगिता  '});assert.equal(res.status,201);const customEvent=await res.json();
 res=await send('/api/events');const customRow=(await res.json()).events.find(e=>e.id===customEvent.id);assert.equal(customRow.type_label,'कबड्डी प्रतियोगिता');assert.equal(customRow.type,'other');
 res=await makeEvent({typeLabel:'   '});assert.equal(res.status,400);
 res=await makeEvent({typeLabel:'x'.repeat(81)});assert.equal(res.status,400);
 res=await makeEvent({typeLabel:'कविता'},viewer);assert.equal(res.status,403);
 res=await post('/api/uploads',{...payload,size:64,contentType:'other',eventId:customEvent.id});assert.equal(res.status,201);
 console.log('PASS: custom event type preserved, required and length validation, owner-only creation, custom event upload.');
 const op=(path,method,body,user=owner,cookie='')=>send(path,{method,headers:{...user,Origin:'https://test.invalid','Content-Type':'application/json',Cookie:cookie},body:JSON.stringify(body)});
 const uploader={'oai-authenticated-user-id':'uploader','oai-authenticated-user-email':'upload@example.test'},manager={'oai-authenticated-user-id':'manager','oai-authenticated-user-email':'manager@example.test'};
 res=await op('/api/team','PUT',{email:uploader['oai-authenticated-user-email'],role:'uploader'},viewer);assert.equal(res.status,403);
 res=await op('/api/team','PUT',{email:uploader['oai-authenticated-user-email'],role:'uploader'});assert.equal(res.status,200);
 res=await op('/api/team','PUT',{email:manager['oai-authenticated-user-email'],role:'event_manager'});assert.equal(res.status,200);
 res=await send('/api/session',{headers:uploader});let rights=await res.json();assert.equal(rights.canUpload,true);assert.equal(rights.canEvents,false);assert.equal(rights.isAdmin,false);
 res=await post('/api/uploads',{...payload,size:64},uploader);assert.equal(res.status,201);
 res=await makeEvent({typeLabel:'Managed event'},uploader);assert.equal(res.status,403);
 res=await makeEvent({typeLabel:'Managed event'},manager);assert.equal(res.status,201);
 res=await post('/api/uploads',{...payload,size:64},manager);assert.equal(res.status,403);
 res=await send('/api/team',{headers:manager});assert.equal(res.status,403);
 res=await send('/api/analytics',{headers:uploader});assert.equal(res.status,403);
 res=await op('/api/devices','PUT',{enabled:true,maxDevices:2,maxScreens:1},manager);assert.equal(res.status,403);
 res=await op('/api/team','PUT',{email:uploader['oai-authenticated-user-email'],role:'remove'});assert.equal(res.status,200);
 res=await post('/api/uploads',{...payload,size:64},uploader);assert.equal(res.status,403);
 res=await post('/api/playback',{entryId:upload.id},{});assert.equal(res.status,201);const guestCookie=res.headers.get('set-cookie').split(';')[0],guestSession=await res.json();
 res=await op('/api/devices','PUT',{enabled:true,maxDevices:2,maxScreens:1});assert.equal(res.status,200);
 res=await post('/api/playback',{entryId:upload.id},{});assert.equal(res.status,401);
 res=await send(`/api/media/${upload.id}`,{headers:viewer});assert.equal(res.status,401);
 res=await send(`/api/media/${upload.id}?session=${guestSession.id}`,{headers:{Cookie:guestCookie}});assert.equal(res.status,401);
 res=await post('/api/playback',{entryId:upload.id},viewer);assert.equal(res.status,201,await res.clone().text());const cookie=res.headers.get('set-cookie').split(';')[0],screen=await res.json();
 res=await op('/api/playback','POST',{entryId:upload.id},viewer,cookie);assert.equal(res.status,409);
 res=await send(`/api/media/${upload.id}?session=${screen.id}`,{headers:{...viewer,Cookie:cookie,Range:'bytes=4-7'}});assert.equal(res.status,206);assert.equal(await res.text(),'ftyp');
 res=await send(`/api/media/${upload.id}?session=${screen.id}`,{headers:{...owner,Cookie:cookie}});assert.equal(res.status,403);
 await db.prepare('UPDATE viewing_sessions SET updated_at=? WHERE id=?').bind(Date.now()-15000,screen.id).run();
 res=await op('/api/playback','PATCH',{id:screen.id,position:15,duration:100,watched:15,completed:false,ended:false},viewer,cookie);assert.equal(res.status,200);
 res=await send('/api/analytics',{headers:owner});const analytics=await res.json();const metric=analytics.summary.find(e=>e.id===upload.id);assert.equal(metric.viewers,1);assert.equal(metric.views,1);assert.equal(metric.watched_seconds,15);
 res=await op('/api/playback','PATCH',{id:screen.id,position:15,duration:100,watched:30,completed:false,ended:false},viewer,cookie);assert.equal(res.status,200);
 const tracked=await db.prepare('SELECT watched FROM viewing_sessions WHERE id=?').bind(screen.id).first();assert.ok(tracked.watched<=16,'duplicate heartbeat must not inflate watch time');
 res=await send('/api/devices',{headers:{...viewer,Cookie:cookie}});const myDevices=await res.json();assert.equal(myDevices.devices.length,1);assert.equal(myDevices.activeScreens,1);
 res=await op('/api/devices','PATCH',{id:myDevices.devices[0].id},owner);assert.equal(res.status,404);
 res=await op('/api/devices','PATCH',{id:myDevices.devices[0].id},viewer,cookie);assert.equal(res.status,200);
 res=await send(`/api/media/${upload.id}?session=${screen.id}`,{headers:{...viewer,Cookie:cookie}});assert.equal(res.status,403);
 res=await send('/api/devices',{headers:viewer});assert.equal((await res.json()).activeScreens,0);
 res=await op('/api/devices','PUT',{enabled:true,maxDevices:1,maxScreens:2});assert.equal(res.status,200);
 res=await post('/api/playback',{entryId:upload.id},viewer);assert.equal(res.status,201);const secondCookie=res.headers.get('set-cookie').split(';')[0],secondScreen=await res.json();
 res=await post('/api/playback',{entryId:upload.id},viewer);assert.equal(res.status,409,'new device beyond cap denied');
 const parallelScreens=await Promise.all([op('/api/playback','POST',{entryId:upload.id},viewer,secondCookie),op('/api/playback','POST',{entryId:upload.id},viewer,secondCookie)]);assert.deepEqual(parallelScreens.map(r=>r.status).sort(),[201,409]);
 res=await op('/api/playback','PATCH',{id:secondScreen.id,position:0,duration:100,watched:0,completed:false,ended:true},viewer,secondCookie);assert.equal(res.status,200);
 res=await op('/api/devices','PUT',{enabled:false,maxDevices:3,maxScreens:1});assert.equal(res.status,200);
 console.log('PASS: team permissions and revocation, sign-in gate, device cap, concurrent screen cap, media ownership, device removal, watch-time bounds and admin-only analytics.');
 // Candidate votes are separate from legacy performance votes and unique per round.
 await db.prepare('UPDATE events SET episode_mode=0,voting_enabled=1,starts_at=?,ends_at=? WHERE id=?').bind(Date.now()-10000,Date.now()+3600000,fixtureEvent).run();
 const candidateBody={eventId:fixtureEvent,name:'Same Name',city:'Nagpur',number:1};
 res=await post('/api/candidates',candidateBody,viewer);assert.equal(res.status,403);
 res=await post('/api/candidates',candidateBody,{});assert.equal(res.status,401);
 res=await post('/api/candidates',candidateBody,manager);assert.equal(res.status,201,await res.clone().text());const c1=await res.json();
 res=await post('/api/candidates',candidateBody);assert.equal(res.status,409);
 res=await post('/api/candidates',{...candidateBody,number:2});assert.equal(res.status,201);const c2=await res.json();
 res=await post(`/api/candidates/${c1.id}/vote`,{},viewer);assert.equal(res.status,403,'candidate mode starts off');
 res=await op('/api/candidates','PATCH',{action:'mode',eventId:fixtureEvent,enabled:true},viewer);assert.equal(res.status,403);
 res=await op('/api/candidates','PATCH',{action:'mode',eventId:fixtureEvent,enabled:true});assert.equal(res.status,200);
 res=await post(`/api/entries/${upload.id}/vote`,{},viewer);assert.equal(res.status,403,'legacy video voting blocked in candidate mode');
 const cv=await Promise.all([post(`/api/candidates/${c1.id}/vote`,{},viewer),post(`/api/candidates/${c2.id}/vote`,{},viewer)]);assert.deepEqual(cv.map(r=>r.status).sort(),[200,409]);
 res=await send('/api/candidates?eventId='+fixtureEvent,{headers:viewer});const cl=(await res.json()).candidates;assert.equal(cl.filter(c=>c.voted).length,1);assert.ok(cl.every(c=>c.scope_voted===1&&!Object.hasOwn(c,'votes')&&!Object.hasOwn(c,'user_id')));
 const chosen=cl.find(c=>c.voted);res=await post(`/api/candidates/${chosen.id}/vote`,{},viewer);assert.equal(res.status,200);
 res=await send('/api/candidates?eventId='+fixtureEvent,{headers:owner});assert.equal((await res.json()).candidates.reduce((n,c)=>n+c.votes,0),1);
 const oldVotes=await db.prepare('SELECT COUNT(*) AS n FROM votes WHERE entry_id=?').bind(upload.id).first();assert.equal(oldVotes.n,2);
 res=await post('/api/candidates',{...candidateBody,episodeGroupId:eventEpisode.id,number:1});assert.equal(res.status,201);const roundCandidate=await res.json();
 res=await op('/api/candidates','PATCH',{action:'assign',candidateId:c1.id,entryId:upload.id});assert.equal(res.status,400,'cross-round video denied');
 res=await op('/api/candidates','PATCH',{action:'assign',candidateId:roundCandidate.id,entryId:upload.id});assert.equal(res.status,200);
 res=await send('/api/entries');assert.equal((await res.json()).entries.find(v=>v.id===upload.id).candidate_id,roundCandidate.id);
 res=await op('/api/episodes','PATCH',{action:'voting',id:eventEpisode.id,enabled:false});assert.equal(res.status,200);
 res=await post(`/api/candidates/${roundCandidate.id}/vote`,{},viewer);assert.equal(res.status,403);
 res=await op('/api/episodes','PATCH',{action:'voting',id:eventEpisode.id,enabled:true});assert.equal(res.status,200);
 res=await post(`/api/candidates/${roundCandidate.id}/vote`,{},viewer);assert.equal(res.status,200,'new round permits one new vote');
 await db.prepare('UPDATE events SET ends_at=? WHERE id=?').bind(Date.now()-1000,fixtureEvent).run();res=await post(`/api/candidates/${roundCandidate.id}/vote`,{},owner);assert.equal(res.status,403);
 res=await send(`/api/candidates/${c1.id}/photo`,{method:'PUT',headers:{...viewer,Origin:'https://test.invalid'},body:'bad'});assert.equal(res.status,403);
 res=await send(`/api/candidates/${c1.id}/photo`,{method:'PUT',headers:{...owner,Origin:'https://test.invalid'},body:'bad'});assert.equal(res.status,400);
 const photo=Uint8Array.from([137,80,78,71,13,10,26,10,0]);res=await send(`/api/candidates/${c1.id}/photo`,{method:'PUT',headers:{...owner,Origin:'https://test.invalid'},body:photo});assert.equal(res.status,200);
 res=await send(`/api/candidates/${c1.id}/photo`);assert.equal(res.status,200);assert.equal(res.headers.get('content-type'),'image/png');
 res=await op('/api/candidates','PATCH',{action:'edit',id:c1.id,name:'Updated name',city:'Raipur'});assert.equal(res.status,200);
 console.log('PASS: candidate permissions, unique numbers, concurrent one-vote-per-round enforcement, private totals, legacy preservation, episode/time gates, video scope and photos.');
}finally{await mf.dispose()}
