'use client';
import {useRef,useState,type ReactNode} from 'react';
import {Play,ChevronLeft,ChevronRight} from 'lucide-react';
import type {ContentType} from '@/lib/catalog';
export type VideoEntry={candidate_id?:string|null;episode_group_id?:string|null;description?:string;duration_seconds?:number;vote_eligible?:number;id:string;event_id:string|null;singer:string;song:string;city:string;content_type:ContentType;genre:string;series_title:string;season:number|null;episode:number|null;votes?:number;voted:number;published_at:number;has_poster?:number;has_thumbnail?:number};
export function Artwork({entry,portrait=false}:{entry:VideoEntry;portrait?:boolean}){
 const [broken,setBroken]=useState(false);const kind=portrait?(entry.has_poster?'poster':entry.has_thumbnail?'thumbnail':null):(entry.has_thumbnail?'thumbnail':entry.has_poster?'poster':null);
 return kind&&!broken?<img loading="lazy" src={`/api/entries/${entry.id}/artwork?kind=${kind}`} alt="" onError={()=>setBroken(true)}/>:<span className="episode-placeholder"><Play size={30}/><small>GONDWANA OTT</small></span>;
}
export function VideoShelf({title,entries,portrait=false,onSelect,renderVote}:{title:string;entries:VideoEntry[];portrait?:boolean;onSelect:(entry:VideoEntry)=>void;renderVote?:(entry:VideoEntry)=>ReactNode}){
 const rail=useRef<HTMLDivElement>(null),[expanded,setExpanded]=useState(false);
 return <section className={`video-shelf ${portrait?'portrait-shelf':'landscape-shelf'}`} aria-label={title}><div className="shelf-heading"><h2>{title}</h2>{entries.length>0&&<div className="shelf-controls"><button type="button" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'कतार में देखें':'सभी देखें'}</button>{!expanded&&<><button type="button" className="rail-step" aria-label={`${title}: पिछले वीडियो`} onClick={()=>rail.current?.scrollBy({left:-rail.current.clientWidth*.8,behavior:'smooth'})}><ChevronLeft size={20}/></button><button type="button" className="rail-step" aria-label={`${title}: अगले वीडियो`} onClick={()=>rail.current?.scrollBy({left:rail.current.clientWidth*.8,behavior:'smooth'})}><ChevronRight size={20}/></button></>}</div>}</div>{entries.length?<div ref={rail} className={`shelf-track ${expanded?'shelf-expanded':''}`}>{entries.map(entry=><article className="shelf-card" key={entry.id}><button type="button" className="shelf-artwork" onClick={()=>onSelect(entry)} aria-label={`${entry.song} देखें`}><Artwork entry={entry} portrait={portrait}/>{!portrait&&<span className="shelf-play"><Play size={22} fill="currentColor"/></span>}{entry.content_type==='series'&&<span className="episode-badge">S{entry.season} · E{entry.episode}</span>}</button><button className="shelf-title" onClick={()=>onSelect(entry)}>{entry.content_type==='series'?`${entry.series_title} — ${entry.song}`:entry.song}</button><p className="shelf-meta">{entry.genre||entry.singer}{!!entry.duration_seconds&&` · ${Math.floor(entry.duration_seconds/60)}:${String(entry.duration_seconds%60).padStart(2,'0')}`}{entry.vote_eligible===0&&' · पूरा कार्यक्रम'}</p>{renderVote&&<div className="shelf-vote">{renderVote(entry)}</div>}</article>)}</div>:<p className="shelf-empty">इस सेक्शन में वीडियो जल्द जोड़ी जाएँगी।</p>}</section>
}
